# Generated by Django 5.2.1 on 2025-05-20 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=30)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
